# docker-compose.yml
#
# copy in /etc/hosts
# 172.16.239.11 dev.mysite.com
#

version: '2'
services:

  mysql:
    image: mysql:5.7
    restart: always
    tty: true
    environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: database
     MYSQL_USER: mysql_user
     MYSQL_PASSWORD: password
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_general_ci]
    container_name: mysql
    networks:
      front:
        ipv4_address: 172.16.239.10
        

  web:
    tty: true
    build: ./apache/
    container_name: web
    depends_on:
      - mysql
    working_dir: "/var/www"
    volumes:
      - ../:/var/www/
      - ./sites-available/:/etc/apache2/sites-available/
    networks:
      front:
        ipv4_address: 172.16.239.11

      
networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
        gateway: 172.16.239.1